apiVersion: v1
kind: Secret
metadata:
  name: genesis-rodriguez-34-secret
  namespace: genesis-rodriguez-34-namespace
type: Opaque
data:
  PORT: ODA4NQ==
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLXNvZnQtY2VsbC1hY205anFzdS1wb29sZXIuc2EtZWFzdC0xLmF3cy5uZW9uLnRlY2g6NTQzMi9BcGxpY2FjaW9uZXNFbXByZXNhcmlhbGVzRW5KYXZh   # en Base64
  DATABASE_USERNAME: bmVvbmRiX293bmVy   # en Base64
  DATABASE_PASSWORD: bnBnX1hSY1kzTW16UDJMYQ==   # en Base64
  RAPIDAPI_KEY: ZTg3MjczZjUzZG1zaDNkZTNkMDlmMzAzZTExOXAxMzk1MWNqc243ODU0ZjhlMzBlY2U=   # en Base64
  RAPIDAPI_FACE_DETECTION_HOST: ZmFjZS1kZXRlY3Rpb24xNC5wLnJhcGlkYXBpLmNvbQ==   # en Base64
  RAPIDAPI_FACE_DETECTION_URL: aHR0cHM6Ly9mYWNlLWRldGVjdGlvbjE0LnAucmFwaWRhcGkuY29tL3YxL3Jlc3VsdHM=   # en Base64
  RAPIDAPI_FACE_ANALYZER_HOST: ZmFjZWFuYWx5emVyLWFpLnAucmFwaWRhcGkuY29t   # en Base64
  RAPIDAPI_FACE_ANALYZER_URL: aHR0cHM6Ly9mYWNlYW5hbHl6ZXItYWkucC5yYXBpZGFwaS5jb20=   # en Base64

# https://base64.guru/converter
# echo -n "valor" | base64
# echo "dmFsb3I=" | base64 --decode
